CREATE TABLE IF NOT EXISTS genres (
id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS artists (
artist_id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL
genres_id SERIAL PRIMARY KEY,
name VARCHAR(80) NOT NULL
